<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="download_subtitles_tests.TestSubtitleCrawler-20211212230553" tests="5" file="download_subtitles_tests.py" time="0.000" timestamp="2021-12-12T23:05:53" failures="0" errors="2" skipped="0">
	<testcase classname="download_subtitles_tests.TestSubtitleCrawler" name="test_save_json_format_in_directory" time="0.000" timestamp="2021-12-12T23:05:53"/>
	<testcase classname="download_subtitles_tests.TestSubtitleCrawler" name="test_search_subtitles_by_id" time="0.000" timestamp="2021-12-12T23:05:53"/>
	<testcase classname="download_subtitles_tests.TestSubtitleCrawler" name="test_search_subtitles_by_id_endpoint_error" time="0.000" timestamp="2021-12-12T23:05:53"/>
	<testcase classname="download_subtitles_tests.TestSubtitleCrawler" name="test_download_subtitles" time="0.000" timestamp="2021-12-12T23:05:53">
		<error type="AttributeError" message="&lt;class 'openSubtitleCrawler.OpenSubtitleCrawler'&gt; does not have the attribute '__download_subtitle_from_proxy'"><![CDATA[Traceback (most recent call last):
  File "c:\program files\python39\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "c:\program files\python39\lib\unittest\case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "c:\program files\python39\lib\unittest\case.py", line 550, in _callTestMethod
    method()
  File "c:\program files\python39\lib\unittest\mock.py", line 1334, in patched
    with self.decoration_helper(patched,
  File "c:\program files\python39\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "c:\program files\python39\lib\unittest\mock.py", line 1316, in decoration_helper
    arg = exit_stack.enter_context(patching)
  File "c:\program files\python39\lib\contextlib.py", line 429, in enter_context
    result = _cm_type.__enter__(cm)
  File "c:\program files\python39\lib\unittest\mock.py", line 1405, in __enter__
    original, local = self.get_original()
  File "c:\program files\python39\lib\unittest\mock.py", line 1378, in get_original
    raise AttributeError(
AttributeError: <class 'openSubtitleCrawler.OpenSubtitleCrawler'> does not have the attribute '__download_subtitle_from_proxy'
]]></error>
	</testcase>
	<testcase classname="download_subtitles_tests.TestSubtitleCrawler" name="test_download_subtitles_endpoint_error" time="0.000" timestamp="2021-12-12T23:05:53">
		<error type="AttributeError" message="&lt;class 'openSubtitleCrawler.OpenSubtitleCrawler'&gt; does not have the attribute '__download_subtitle_from_proxy'"><![CDATA[Traceback (most recent call last):
  File "c:\program files\python39\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "c:\program files\python39\lib\unittest\case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "c:\program files\python39\lib\unittest\case.py", line 550, in _callTestMethod
    method()
  File "c:\program files\python39\lib\unittest\mock.py", line 1334, in patched
    with self.decoration_helper(patched,
  File "c:\program files\python39\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "c:\program files\python39\lib\unittest\mock.py", line 1316, in decoration_helper
    arg = exit_stack.enter_context(patching)
  File "c:\program files\python39\lib\contextlib.py", line 429, in enter_context
    result = _cm_type.__enter__(cm)
  File "c:\program files\python39\lib\unittest\mock.py", line 1405, in __enter__
    original, local = self.get_original()
  File "c:\program files\python39\lib\unittest\mock.py", line 1378, in get_original
    raise AttributeError(
AttributeError: <class 'openSubtitleCrawler.OpenSubtitleCrawler'> does not have the attribute '__download_subtitle_from_proxy'
]]></error>
	</testcase>
</testsuite>
